apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v8iqm3e0y-java-springboot
  janus-idp.io/tekton: v8iqm3e0y-java-springboot
  backstage.io/kubernetes-id: v8iqm3e0y-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v8iqm3e0y-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
